In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [3]:
np.random.seed(42)

In [4]:
import pandas as pd
import sklearn

In [5]:
# db_benign refers to the benign dataset of the doorbell. Other variable names follow a similar nomenclature.
db_benign = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\benign_traffic.csv", sep = ',')
db_benign.head()

MI_dir_L5_weight  MI_dir_L5_mean  MI_dir_L5_variance  MI_dir_L3_weight  \
0          1.000000       60.000000            0.000000          1.000000   
1          1.000000      354.000000            0.000000          1.000000   
2          1.857879      360.458980           35.789338          1.912127   
3          1.000000      337.000000            0.000000          1.000000   
4          1.680223      172.140917        18487.448750          1.793580   

   MI_dir_L3_mean  MI_dir_L3_variance  MI_dir_L1_weight  MI_dir_L1_mean  \
0       60.000000            0.000000          1.000000       60.000000   
1      354.000000            0.000000          1.000000      354.000000   
2      360.275733           35.923972          1.969807      360.091968   
3      337.000000            0.000000          1.000000      337.000000   
4      182.560279        18928.175300          1.925828      193.165753   

   MI_dir_L1_variance  MI_dir_L0.1_weight    ...      HpHp_L0.1_covariance  \
0            0.000000            1.000000    ...                       0.0   
1            0.000000            1.000000    ...                       0.0   
2           35.991542            1.996939    ...                       0.0   
3            0.000000            1.000000    ...                       0.0   
4        19153.795810            1.992323    ...                       0.0   

   HpHp_L0.1_pcc  HpHp_L0.01_weight  HpHp_L0.01_mean  HpHp_L0.01_std  \
0            0.0           1.000000        60.000000        0.000000   
1            0.0           5.319895       344.262695        4.710446   
2            0.0           6.318264       347.703087        9.034660   
3            0.0           1.000000       337.000000        0.000000   
4            0.0           1.000000        60.000000        0.000000   

   HpHp_L0.01_magnitude  HpHp_L0.01_radius  HpHp_L0.01_covariance  \
0             60.000000           0.000000                    0.0   
1            344.262695          22.188299                    0.0   
2            347.703087          81.625077                    0.0   
3            337.000000           0.000000                    0.0   
4             60.000000           0.000000                    0.0   

   HpHp_L0.01_pcc       type  
0             0.0  db benign  
1             0.0  db benign  
2             0.0  db benign  
3             0.0  db benign  
4             0.0  db benign  

[5 rows x 116 columns]

In [6]:
db_tcp = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\tcp.csv", sep = ',')
db_combo = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\combo.csv", sep = ',')
db_junk = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\junk.csv", sep = ',')
db_scan = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\scan.csv", sep = ',')
db_udp = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\udp.csv", sep = ',')

In [7]:
db_merge = db_benign.append([db_tcp, db_combo, db_junk, db_scan, db_udp],ignore_index=True)
db_merge.to_csv('C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\doorbellmerge.csv',index=False)
pd.crosstab(db_merge.type, columns = 'type')

col_0        type
type             
db benign   49548
db combo    59718
db junk     29068
db scan     29849
db tcp      92141
db udp     105874

In [8]:
db_merge['type'] = db_merge['type'].map({'db benign': 0, 'db combo': 1, 'db junk': 2, 'db scan': 3, 'db tcp': 4, 'db udp': 5})
pd.crosstab(db_merge.type, columns = 'type')

col_0    type
type         
0       49548
1       59718
2       29068
3       29849
4       92141
5      105874

In [58]:
db_merge['device'] = 'doorbell'

In [59]:
db_merge.head()

MI_dir_L5_weight  MI_dir_L5_mean  MI_dir_L5_variance  MI_dir_L3_weight  \
0          1.000000       60.000000            0.000000          1.000000   
1          1.000000      354.000000            0.000000          1.000000   
2          1.857879      360.458980           35.789338          1.912127   
3          1.000000      337.000000            0.000000          1.000000   
4          1.680223      172.140917        18487.448750          1.793580   

   MI_dir_L3_mean  MI_dir_L3_variance  MI_dir_L1_weight  MI_dir_L1_mean  \
0       60.000000            0.000000          1.000000       60.000000   
1      354.000000            0.000000          1.000000      354.000000   
2      360.275733           35.923972          1.969807      360.091968   
3      337.000000            0.000000          1.000000      337.000000   
4      182.560279        18928.175300          1.925828      193.165753   

   MI_dir_L1_variance  MI_dir_L0.1_weight    ...     HpHp_L0.1_pcc  \
0            0.000000            1.000000    ...               0.0   
1            0.000000            1.000000    ...               0.0   
2           35.991542            1.996939    ...               0.0   
3            0.000000            1.000000    ...               0.0   
4        19153.795810            1.992323    ...               0.0   

   HpHp_L0.01_weight  HpHp_L0.01_mean  HpHp_L0.01_std  HpHp_L0.01_magnitude  \
0           1.000000        60.000000        0.000000             60.000000   
1           5.319895       344.262695        4.710446            344.262695   
2           6.318264       347.703087        9.034660            347.703087   
3           1.000000       337.000000        0.000000            337.000000   
4           1.000000        60.000000        0.000000             60.000000   

   HpHp_L0.01_radius  HpHp_L0.01_covariance  HpHp_L0.01_pcc  type    device  
0           0.000000                    0.0             0.0     0  doorbell  
1          22.188299                    0.0             0.0     0  doorbell  
2          81.625077                    0.0             0.0     0  doorbell  
3           0.000000                    0.0             0.0     0  doorbell  
4           0.000000                    0.0             0.0     0  doorbell  

[5 rows x 117 columns]

In [ ]:
# function to search for singular values

def which(self):
    try:
        self = list(iter(self))
    except TypeError as e:
        raise Exception("""'which' method can only be applied to iterables.
        {}""".format(str(e)))
    indices = [i for i, x in enumerate(self) if bool(x) == True]
    return(indices)

In [ ]:
legitcols=which(db_merge.apply(pd.Series.nunique) != 1) 
len(legitcols)

In [60]:
dataset = db_merge.values
X = dataset[:,0:115].astype(float)
Y = dataset[:,115].astype(int)

In [61]:
from sklearn import preprocessing
X_scaled = preprocessing.scale(X)

C:\Users\KISHALAY\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:176: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [62]:
# One Hot Encoding

from keras.utils import to_categorical
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder 

encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
dummy_y = np_utils.to_categorical(encoded_Y)

In [63]:
# Train - Test Split

from sklearn.model_selection import train_test_split
db_train, db_test, y_train, y_test = sklearn.model_selection.train_test_split(X_scaled,dummy_y, test_size = 0.25)
 

In [64]:
pd.crosstab(Y,columns='label')

col_0   label
row_0        
0       49548
1       59718
2       29068
3       29849
4       92141
5      105874

In [65]:
# Model definiton 
# This model has given the best training accuracy (91%) till now. The accuracy improved after Encoding, increasing a hidden layer, and changing the activation function for some layers.
# According to DataScience article, Softmax is the best for multiclass classification. Maybe use Softmax for another layer??

model1 = Sequential()
model1.add(Dense(200, input_dim=115, activation='softmax'))
model1.add(Dense(200, activation='relu'))
model1.add(Dense(150, activation='relu'))
model1.add(Dense(6, activation='softmax'))

In [66]:
# model compilation

model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [67]:
# Running the model (using fewer epochs, to save time)
# TODO : Increase number of epochs and maybe decrease batch size to see if accuracy improves. Adding another layer is also an option.
model1.fit(db_train, y_train, epochs=1, batch_size=25)

Epoch 1/1
274648/274648 [==============================] - 21s 78us/step - loss: 0.1436 - acc: 0.9051


In [68]:
# model1 evaluation
scores = model1.evaluate(db_train, y_train)
print("\n%s: %.2f%%" % (model1.metrics_names[1], scores[1]*100))

274648/274648 [==============================] - 7s 27us/step

acc: 91.16%


In [69]:
predictions = model1.predict(db_test)
#rounded = [round(x[0]) for x in predictions]

In [70]:
for i in range(len(predictions)):
    a = 0
    indexpred = 0
    for j in range(6):
        if predictions[i][j] > a:
            a = predictions[i][j]
            indexpred = j
            
    for k in range(6):
        if k==indexpred:
            predictions[i][k] = 1
        else:
            predictions[i][k] = 0
print(predictions)

[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 ...
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]


In [71]:
index_pred = np.where(np.in1d(predictions, [1]))[0]
index_pred

array([     5,     11,     17, ..., 549284, 549293, 549299], dtype=int64)

In [72]:
index_pred = index_pred%6
index_pred

array([5, 5, 5, ..., 2, 5, 5], dtype=int64)

In [73]:
index = np.where(np.in1d(y_test, [1]))[0]
index = index%6
index

array([5, 5, 5, ..., 2, 5, 5], dtype=int64)

In the next cell, we generate the confusion matrix of true values against predictions. The rows are the true values and the columns represent the predictions.
We next calculate the specificity for each label. We avoid calculating accuracy because ....**TODO**(from DST 2 project)

In [74]:
#pd.crosstab(index_pred-index, columns="Residual")

from  sklearn.metrics import confusion_matrix
matrix = confusion_matrix(index, index_pred)
matrix

array([[12373,     0,     3,     2,     0,     1],
       [    4, 14851,   165,     9,     0,     0],
       [    1,   913,  6416,     7,     0,     0],
       [   11,     3,    34,  7431,     1,     5],
       [   20,     0,     1,     1,     0, 22809],
       [   11,     2,     2,     3,     0, 26471]], dtype=int64)

In [89]:
#for i in range(6):
def specificity(confusion_matrix,i):
    a=np.array(confusion_matrix)
    cols = (np.sum(a, axis=0))
    rows = (np.sum(a, axis=1))
    true_positives = confusion_matrix[i][i]
    true_negatives = sum(sum(confusion_matrix)) - rows[i] - cols[i] + confusion_matrix[i][i]
    false_positives = cols[i] - true_positives
    return true_negatives/(true_negatives+false_positives)
    
for i in range(6):
    print(specificity(matrix,i))

0.9994063482840939
0.9880032932136277
0.9975656965076651
0.9997382977457919
0.9999854479838182
0.6493290911606031


In [79]:
a=np.array(matrix)
cols = (np.sum(a, axis=0))
rows = (np.sum(a, axis=1))
print(rows, cols)

[12379 15029  7337  7485 22831 26489] [12420 15769  6621  7453     1 49286]


In [90]:
def sensitivity(confusion_matrix,i):
    true_positives = confusion_matrix[i][i]
    false_negatives = sum(confusion_matrix[i]) - true_positives
    return true_positives/(true_positives+false_negatives)
    
for i in range(6):
    print(sensitivity(matrix,i))

0.9995153081832135
0.98815623128618
0.8744718549816001
0.9927855711422846
0.0
0.9993204726490241


Most of the sensitivity values are quite good, except for the 5th one. If we examine that row of the confusion matrix, we observe that most of the TCP attacks have been misclassified as UDP attacks. This **(MAYBE???)** needs further study. 
Also, the converse **DOES NOT** occur, i.e, most UDP connections are classified correctly. 
**NEED TO WRITE SOME MORE ON THIS**

In [ ]:
ts_benign = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\benign_traffic.csv", sep = ',')
ts_tcp = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\tcp.csv", sep = ',')
ts_combo = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\combo.csv", sep = ',')
ts_junk = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\junk.csv", sep = ',')
ts_scan = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\scan.csv", sep = ',')
ts_udp = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\udp.csv", sep = ',')