In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [3]:
np.random.seed(42)

In [4]:
import pandas as pd
import sklearn

In [8]:
# db_benign refers to the benign dataset of the doorbell. Other variable names follow a similar nomenclature.
db_benign = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\benign_traffic.csv", sep = ',')
db_benign.head()

MI_dir_L5_weight  MI_dir_L5_mean  MI_dir_L5_variance  MI_dir_L3_weight  \
0          1.000000       60.000000            0.000000          1.000000   
1          1.000000      354.000000            0.000000          1.000000   
2          1.857879      360.458980           35.789338          1.912127   
3          1.000000      337.000000            0.000000          1.000000   
4          1.680223      172.140917        18487.448750          1.793580   

   MI_dir_L3_mean  MI_dir_L3_variance  MI_dir_L1_weight  MI_dir_L1_mean  \
0       60.000000            0.000000          1.000000       60.000000   
1      354.000000            0.000000          1.000000      354.000000   
2      360.275733           35.923972          1.969807      360.091968   
3      337.000000            0.000000          1.000000      337.000000   
4      182.560279        18928.175300          1.925828      193.165753   

   MI_dir_L1_variance  MI_dir_L0.1_weight   ...    HpHp_L0.1_covariance  \
0            0.000000            1.000000   ...                     0.0   
1            0.000000            1.000000   ...                     0.0   
2           35.991542            1.996939   ...                     0.0   
3            0.000000            1.000000   ...                     0.0   
4        19153.795810            1.992323   ...                     0.0   

   HpHp_L0.1_pcc  HpHp_L0.01_weight  HpHp_L0.01_mean  HpHp_L0.01_std  \
0            0.0           1.000000        60.000000        0.000000   
1            0.0           5.319895       344.262695        4.710446   
2            0.0           6.318264       347.703087        9.034660   
3            0.0           1.000000       337.000000        0.000000   
4            0.0           1.000000        60.000000        0.000000   

   HpHp_L0.01_magnitude  HpHp_L0.01_radius  HpHp_L0.01_covariance  \
0             60.000000           0.000000                    0.0   
1            344.262695          22.188299                    0.0   
2            347.703087          81.625077                    0.0   
3            337.000000           0.000000                    0.0   
4             60.000000           0.000000                    0.0   

   HpHp_L0.01_pcc    type  
0             0.0  benign  
1             0.0  benign  
2             0.0  benign  
3             0.0  benign  
4             0.0  benign  

[5 rows x 116 columns]

In [9]:
db_tcp = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\tcp.csv", sep = ',')
db_combo = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\combo.csv", sep = ',')
db_junk = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\junk.csv", sep = ',')
db_scan = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\scan.csv", sep = ',')
db_udp = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\udp.csv", sep = ',')

In [10]:
db_merge = db_benign.append([db_tcp, db_combo, db_junk, db_scan, db_udp],ignore_index=True)
db_merge.to_csv('C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Doorbell\\doorbellmerge.csv',index=False)
pd.crosstab(db_merge.type, columns = 'type')

col_0     type
type          
 combo   59718
 junk    29068
 scan    29849
 tcp     92141
 udp    105874
benign   49548

In [11]:
#db_merge['type'] = db_merge['type'].map({'benign': 0, 'combo': 1, 'junk': 2, 'scan': 3, 'tcp': 4, 'udp': 5})
#pd.crosstab(db_merge.type, columns = 'type')

In [12]:
db_merge['device'] = 'doorbell'

In [13]:
db_merge.head()

MI_dir_L5_weight  MI_dir_L5_mean  MI_dir_L5_variance  MI_dir_L3_weight  \
0          1.000000       60.000000            0.000000          1.000000   
1          1.000000      354.000000            0.000000          1.000000   
2          1.857879      360.458980           35.789338          1.912127   
3          1.000000      337.000000            0.000000          1.000000   
4          1.680223      172.140917        18487.448750          1.793580   

   MI_dir_L3_mean  MI_dir_L3_variance  MI_dir_L1_weight  MI_dir_L1_mean  \
0       60.000000            0.000000          1.000000       60.000000   
1      354.000000            0.000000          1.000000      354.000000   
2      360.275733           35.923972          1.969807      360.091968   
3      337.000000            0.000000          1.000000      337.000000   
4      182.560279        18928.175300          1.925828      193.165753   

   MI_dir_L1_variance  MI_dir_L0.1_weight    ...     HpHp_L0.1_pcc  \
0            0.000000            1.000000    ...               0.0   
1            0.000000            1.000000    ...               0.0   
2           35.991542            1.996939    ...               0.0   
3            0.000000            1.000000    ...               0.0   
4        19153.795810            1.992323    ...               0.0   

   HpHp_L0.01_weight  HpHp_L0.01_mean  HpHp_L0.01_std  HpHp_L0.01_magnitude  \
0           1.000000        60.000000        0.000000             60.000000   
1           5.319895       344.262695        4.710446            344.262695   
2           6.318264       347.703087        9.034660            347.703087   
3           1.000000       337.000000        0.000000            337.000000   
4           1.000000        60.000000        0.000000             60.000000   

   HpHp_L0.01_radius  HpHp_L0.01_covariance  HpHp_L0.01_pcc    type    device  
0           0.000000                    0.0             0.0  benign  doorbell  
1          22.188299                    0.0             0.0  benign  doorbell  
2          81.625077                    0.0             0.0  benign  doorbell  
3           0.000000                    0.0             0.0  benign  doorbell  
4           0.000000                    0.0             0.0  benign  doorbell  

[5 rows x 117 columns]

In [ ]:
# function to search for singular values

def which(self):
    try:
        self = list(iter(self))
    except TypeError as e:
        raise Exception("""'which' method can only be applied to iterables.
        {}""".format(str(e)))
    indices = [i for i, x in enumerate(self) if bool(x) == True]
    return(indices)

In [ ]:
legitcols=which(db_merge.apply(pd.Series.nunique) != 1) 
len(legitcols)

In [14]:
dataset = db_merge.values
X = dataset[:,0:115].astype(float)
Y = dataset[:,115]

In [15]:
from sklearn import preprocessing
X_scaled = preprocessing.scale(X)

C:\Users\KISHALAY\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:176: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [16]:
#X_scaled

In [17]:
# One Hot Encoding

from keras.utils import to_categorical
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder 

encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
dummy_y = np_utils.to_categorical(encoded_Y)

In [18]:
device_label = dataset[:,116]

In [ ]:
#device_label

In [ ]:
#X_scaled['device_label'] = 'doorbell'

In [19]:
# Train - Test Split

from sklearn.model_selection import train_test_split
db_train, db_test, y_train, y_test, z_train, z_test = sklearn.model_selection.train_test_split(X_scaled, dummy_y, device_label, test_size = 0.25)
 

In [ ]:
pd.crosstab(Y,columns='label')

In [20]:
# Model definiton 
# This model has given the best training accuracy (91%) till now. The accuracy improved after Encoding, increasing a hidden layer, and changing the activation function for some layers.
# According to DataScience article, Softmax is the best for multiclass classification. Maybe use Softmax for another layer??

model1 = Sequential()
model1.add(Dense(200, input_dim=115, activation='softmax'))
model1.add(Dense(200, activation='relu'))
model1.add(Dense(150, activation='relu'))
model1.add(Dense(6, activation='softmax'))

In [21]:
# model compilation

model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
# Running the model (using fewer epochs, to save time)
# TODO : Increase number of epochs and maybe decrease batch size to see if accuracy improves. Adding another layer is also an option.
model1.fit(db_train, y_train, epochs=5, batch_size=25)

Epoch 1/5
274648/274648 [==============================] - 21s 75us/step - loss: 0.1440 - acc: 0.9049
Epoch 2/5
274648/274648 [==============================] - 19s 69us/step - loss: 0.1341 - acc: 0.9114
Epoch 3/5
274648/274648 [==============================] - 19s 69us/step - loss: 0.1326 - acc: 0.9123
Epoch 4/5
274648/274648 [==============================] - 20s 72us/step - loss: 0.1318 - acc: 0.9126
Epoch 5/5
274648/274648 [==============================] - 20s 72us/step - loss: 0.1315 - acc: 0.9128


In [23]:
# model1 evaluation
scores = model1.evaluate(db_train, y_train)
print("\n%s: %.2f%%" % (model1.metrics_names[1], scores[1]*100))

274648/274648 [==============================] - 7s 24us/step

acc: 91.26%


In [24]:
predictions = model1.predict(db_test)
#rounded = [round(x[0]) for x in predictions]

In [25]:
for i in range(len(predictions)):
    a = 0
    indexpred = 0
    for j in range(6):
        if predictions[i][j] > a:
            a = predictions[i][j]
            indexpred = j
            
    for k in range(6):
        if k==indexpred:
            predictions[i][k] = 1
        else:
            predictions[i][k] = 0
print(predictions)

[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [26]:
index_pred = np.where(np.in1d(predictions, [1]))[0]
index_pred

array([     4,     10,     17, ..., 549286, 549292, 549298], dtype=int64)

In [27]:
index_pred = index_pred%6
index_pred

array([4, 4, 5, ..., 4, 4, 4], dtype=int64)

In [28]:
#z = 0
#for i in range(len(index)):
#    if index[i] == 4:
#        z = z+1
    
#print(z)

In [29]:
index = np.where(np.in1d(y_test, [1]))[0]
index = index%6
index

array([4, 3, 5, ..., 4, 4, 4], dtype=int64)

In the next cell, we generate the confusion matrix of true values against predictions. The rows are the true values and the columns represent the predictions.
We next calculate the specificity for each label. We avoid calculating accuracy because ....**TODO**(from DST 2 project)

In [30]:
#pd.crosstab(index_pred-index, columns="Residual")

from  sklearn.metrics import confusion_matrix
matrix = confusion_matrix(index, index_pred)
matrix

array([[14762,   243,    14,     0,     0,     1],
       [  607,  6643,     7,     0,     0,     3],
       [    0,     2,  7479,     0,     0,    12],
       [    2,     0,     8,     9, 22887,     5],
       [    0,     0,     6,     1, 26417,     5],
       [    0,     3,     0,     0,    22, 12412]], dtype=int64)

In [31]:
#for i in range(6):
def specificity(confusion_matrix,i):
    a=np.array(confusion_matrix)
    cols = (np.sum(a, axis=0))
    rows = (np.sum(a, axis=1))
    true_positives = confusion_matrix[i][i]
    true_negatives = sum(sum(confusion_matrix)) - rows[i] - cols[i] + confusion_matrix[i][i]
    false_positives = cols[i] - true_positives
    return true_negatives/(true_negatives+false_positives)
    
for i in range(6):
    print(specificity(matrix,i))

0.9920423363386907
0.9970577767232175
0.9995836158797007
0.9999854310231793
0.6482087191535757
0.99967135616144


In [32]:
#a=np.array(matrix)
#cols = (np.sum(a, axis=0))
#rows = (np.sum(a, axis=1))
#print(rows, cols)

In [33]:
def sensitivity(confusion_matrix,i):
    true_positives = confusion_matrix[i][i]
    false_negatives = sum(confusion_matrix[i]) - true_positives
    return true_positives/(true_positives+false_negatives)
    
for i in range(6):
    print(sensitivity(matrix,i))

0.9828229027962716
0.9150137741046832
0.998131589483518
0.00039282440748985203
0.9995459533088653
0.9979898689394548


In [ ]:
matrix_device = confusion_matrix(index, index_pred)

In [34]:
for i in range(len(index)):
    if index[i] != index_pred[i]:
        print(index[i],index_pred[i],z_test[i])

3 4 doorbell
3 4 doorbell
5 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 5 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 2 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 5 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell

3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
4 5 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

1 0 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 2 doorbell
3 4 doorbell

3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
1 0 doorbell
3 4 doorbell
0 1 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell
3 4 doorbell

Most of the sensitivity values are quite good, except for the 5th one. If we examine that row of the confusion matrix, we observe that most of the TCP attacks have been misclassified as UDP attacks. This **(MAYBE???)** needs further study. 
Also, the converse **DOES NOT** occur, i.e, most UDP connections are classified correctly. 
**NEED TO WRITE SOME MORE ON THIS**

In [ ]:
ts_benign = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\benign_traffic.csv", sep = ',')
ts_tcp = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\tcp.csv", sep = ',')
ts_combo = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\combo.csv", sep = ',')
ts_junk = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\junk.csv", sep = ',')
ts_scan = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\scan.csv", sep = ',')
ts_udp = pd.read_csv("C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\udp.csv", sep = ',')

In [ ]:
ts_benign['type'] = 'benign'
ts_tcp['type'] = 'tcp'
ts_combo['type'] = 'combo'
ts_junk['type'] = 'junk'
ts_scan['type'] = 'scan'
ts_udp['type'] = 'udp'

In [ ]:
ts_merge = ts_benign.append([ts_tcp, ts_combo, ts_junk, ts_scan, ts_udp],ignore_index=True)
ts_merge.to_csv('C:\\Users\\KISHALAY\\Desktop\\tensorflow dataset\\Thermostat\\thermomerge.csv',index=False)
pd.crosstab(ts_merge.type, columns = 'type')

In [ ]:
ts_merge['device'] = 'Thermostat'

In [ ]:
ts_merge.head()

In [48]:
min(len(db_udp),len(db_tcp))*3 - 275908

515

In [46]:
counter = 0
for i in range(min(len(db_tcp),len(db_udp))):
    for j in range(116):
         if db_tcp.iloc[i][j] == db_udp.iloc[i][j]:
            counter = counter + 1
                
print(counter)

275908


2


In [ ]:
from scipy import stats
for i in range(min())