# <h1><center>DATA SCIENCE TOOLBOX (COURSEWORK 4)</center></h1>

## <h2><center>KISHALAY BANERJEE, SHANGLIN ZOU, KATARZYNA STANIEWICZ</center></h2>

<h3><center>DEEP LEARNING (USING NEURAL NETWORKS)</center></h3>

In this assignment, we are supposed to implement Deep Learning in the context of cybersecurity. Keeping this objective in mind, we have attempted to write a Neural Networks model, to run on suitably chosen data set. A detailed description of the data set and the model is provided in the report. 

In Code Chunk 1, we load some useful Python libraries, and set a random seed for our computations.

In [1]:
#CODE CHUNK 1

import pandas as pd
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
from keras.utils import to_categorical
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from scipy import stats
# fix random seed for reproducibility
np.random.seed(7)

C:\Users\seeml\Anaconda3\lib\site-packages\h5py\__init__.py:72: UserWarning: h5py is running against HDF5 1.10.2 when it was built against 1.10.3, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Using TensorFlow backend.


In Code Chunk 2, we load the data in csv format. We also convert the data from a dataframe to an array. 

In [2]:
#CODE CHUNK 2

df = pd.read_csv('C:/Users/seeml/Desktop/DATA.csv', error_bad_lines = False)
dataset = df.values


In Code Chunk 3, we extract the numeric columns from the data and standardise them. This is done because data standardisation is somewhat of a pre-requisite for neural networks, and is highly recommended.

In [3]:
#CODE CHUNK 3

scaler = preprocessing.StandardScaler()
X_scaled = scaler.fit_transform(df.iloc[:,0:115])


In Code Chunk 4, we extract the column containing attack labels from the data set.

In [4]:
#CODE CHUNK 4

Y = dataset[:,115]

In Code Chunk 5, we perform One Hot Encoding on the labels, since they fall under categorical data.

In [5]:
#CODE CHUNK 5

encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
dummy_y = np_utils.to_categorical(encoded_Y)

In Code Chunk 6, we are splitting the data into Training and Test data sets. We are keeping 25% of the data as the test set.

In [6]:
#CODE CHUNK 6

X_train, X_test, y_train, y_test =train_test_split(X_scaled,dummy_y, test_size = 0.25)

In Code Chunk 7, we are running a loop to check which batch size gives the best values for accuracy. All of this calculated for a constant number of epochs (=50).
A plot of the batch sizes against accuracy is provided in the main report.

In [7]:
#CODE CHUNK 7

batch_size = [250,500,1000,1500,2000,3000,4000]
acc = list()
loss = list()
for i in batch_size:
    print("batch : " + str(i))
    model = Sequential()
    model.add(Dense(250, input_dim=115, activation='relu'))
    model.add(Dense(250, activation='relu'))
    model.add(Dense(25, activation='sigmoid'))
    model.add(Dense(6, activation='softmax'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.fit(X_train, y_train, epochs=50, batch_size=i)
    scaledtorscores = model.evaluate(X_train, y_train)
    loss.append(scaledtorscores[0])
    acc.append(scaledtorscores[1]*100)
    print("\n%s: %.2f%%" % (model.metrics_names[1], scaledtorscores[1]*100))
print(acc)
print(loss)

batch : 250
Epoch 1/50
1006466/1006466 [==============================] - 14s 14us/step - loss: 0.1242 - acc: 0.9203
Epoch 2/50
1006466/1006466 [==============================] - 14s 14us/step - loss: 0.1071 - acc: 0.9285
Epoch 3/50
1006466/1006466 [==============================] - 14s 14us/step - loss: 0.1058 - acc: 0.9292
Epoch 4/50
1006466/1006466 [==============================] - 14s 14us/step - loss: 0.1051 - acc: 0.9295
Epoch 5/50
1006466/1006466 [==============================] - 14s 14us/step - loss: 0.1050 - acc: 0.9296
Epoch 6/50
1006466/1006466 [==============================] - 15s 15us/step - loss: 0.1049 - acc: 0.9296
Epoch 7/50
1006466/1006466 [==============================] - 16s 15us/step - loss: 0.1044 - acc: 0.9298
Epoch 8/50
1006466/1006466 [==============================] - 15s 15us/step - loss: 0.1044 - acc: 0.9298
Epoch 9/50
1006466/1006466 [==============================] - 17s 16us/step - loss: 0.1044 - acc: 0.9298
Epoch 10/50
1006466/1006466 [==============

1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1038 - acc: 0.9302
Epoch 28/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1034 - acc: 0.9302
Epoch 29/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1035 - acc: 0.9303
Epoch 30/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1036 - acc: 0.9302
Epoch 31/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1034 - acc: 0.9303
Epoch 32/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1033 - acc: 0.9303
Epoch 33/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1036 - acc: 0.9301
Epoch 34/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1036 - acc: 0.9303
Epoch 35/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1034 - acc: 0.9303
Epoch 36/50
1006466/1006466 [=============================

1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1120 - acc: 0.9282
Epoch 3/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1066 - acc: 0.9293
Epoch 4/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1054 - acc: 0.9296
Epoch 5/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1048 - acc: 0.9298
Epoch 6/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1044 - acc: 0.9299
Epoch 7/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1045 - acc: 0.9299
Epoch 8/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1039 - acc: 0.9301
Epoch 9/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1034 - acc: 0.9303
Epoch 10/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1036 - acc: 0.9301
Epoch 11/50
1006466/1006466 [==============================] - 13

1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1028 - acc: 0.9304
Epoch 29/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1029 - acc: 0.9304
Epoch 30/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1037 - acc: 0.9302
Epoch 31/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1027 - acc: 0.9305
Epoch 32/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1033 - acc: 0.9303
Epoch 33/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1027 - acc: 0.9304
Epoch 34/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1043 - acc: 0.9301
Epoch 35/50
1006466/1006466 [==============================] - 13s 12us/step - loss: 0.1027 - acc: 0.9305
Epoch 36/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1029 - acc: 0.9304
Epoch 37/50
1006466/1006466 [=============================

1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1368 - acc: 0.9167
Epoch 4/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1184 - acc: 0.9275
Epoch 5/50
1006466/1006466 [==============================] - 14s 14us/step - loss: 0.1105 - acc: 0.9288
Epoch 6/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1077 - acc: 0.9295
Epoch 7/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1064 - acc: 0.9298
Epoch 8/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1058 - acc: 0.9298
Epoch 9/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1055 - acc: 0.9298
Epoch 10/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1047 - acc: 0.9301
Epoch 11/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1044 - acc: 0.9301 0s - loss: 0.1045 - acc: 0
Epoch 12/50
1006466/1006466 [========

In Code Chunk 8, we define our model. We decided on 4 layers with their respective activation functions after some trial and error with various combinations. 

In [8]:
#CODE CHUNK 8
model1 = Sequential()
model1.add(Dense(250, input_dim=115, activation='relu'))
model1.add(Dense(250, activation='relu'))
model1.add(Dense(25, activation='sigmoid'))
model1.add(Dense(6, activation='softmax'))

In Code Chunk 9, we compile the model we have just written. We have chosen the loss and optimiser after some deliberation, which have been detailed in the report.

In [9]:
#CODE CHUNK 9

model1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In Code Chunk 10, we are fitting our model on the training data, and obtaining values for the accuracy obtained at each epoch.   

In [10]:
#CODE CHUNK 10

model1.fit(X_train, y_train, epochs=50, batch_size=1500)
scores = model1.evaluate(X_train,y_train)

Epoch 1/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.1621 - acc: 0.9033
Epoch 2/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1206 - acc: 0.9261
Epoch 3/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1088 - acc: 0.9291
Epoch 4/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1062 - acc: 0.9295
Epoch 5/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1052 - acc: 0.9298
Epoch 6/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1046 - acc: 0.9300
Epoch 7/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1043 - acc: 0.9300
Epoch 8/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1039 - acc: 0.9301
Epoch 9/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.1036 - acc: 0.9302
Epoch 10/50
1006466/1006466 [==========================

In Code Chunk 11, our model is generating predictions of the test data set. 

In [11]:
#CODE CHUNK 11

predictions = model1.predict(X_test)
predictions

array([[1.74681709e-08, 1.15118991e-03, 9.98845816e-01, 2.74359508e-07,
        1.21515683e-07, 2.65752146e-06],
       [1.02549791e-06, 9.99883175e-01, 1.12591115e-04, 1.56158208e-07,
        3.09858308e-07, 2.63331344e-06],
       [2.02766514e-05, 1.01627065e-05, 2.57692341e-06, 8.71282793e-07,
        4.73164260e-01, 5.26801825e-01],
       ...,
       [3.04167513e-09, 9.99986172e-01, 1.37643910e-05, 1.86343563e-09,
        3.77032272e-09, 8.34320844e-08],
       [5.64243186e-09, 9.99969244e-01, 3.05806279e-05, 4.01430755e-09,
        6.80386547e-09, 1.40664781e-07],
       [7.44478168e-09, 2.78336782e-04, 9.99720752e-01, 9.67677352e-08,
        3.03350056e-08, 6.94766356e-07]], dtype=float32)

For Code Chunk 12. 
Unlike the test labels, our predicted labels aren't in the form of 0's or 1's. Rather, they give the values of the probability of a particular observation belonging to a particular class. For comparison, we need to convert them to binary. To do this, we run a nested loop system. In the outer loop, we are storing the index (position) of the highest numeric value in that row. In the inner loop, we are converting that value to 1, and converting the rest of the values of that row to 0. This is logical because, the prediction with the highest numeric value is expected to be the most probable class of that particular observation.

In [12]:
#CODE CHUNK 12

prediction = predictions
for i in range(len(prediction)):
    a = 0
    indexpred = 0
    for j in range(6):
        if prediction[i][j] > a:
            a = prediction[i][j]
            indexpred = j
            
    for k in range(6):
        if k==indexpred:
            prediction[i][k] = 1
        else:
            prediction[i][k] = 0
print(prediction)

[[0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 ...
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In Code Chunk 13, we are extracting the index values of each of the predictions (after binarising) made in the previous step.  

In [13]:
#CODE CHUNK 13

index_pred = np.where(np.in1d(prediction, [1]))[0]
index_pred

array([      2,       7,      17, ..., 2012917, 2012923, 2012930],
      dtype=int64)

In Code Chunk 14, we are taking the mod of the index values with respect to 6, so that we get values between 0 and 5. This is because we are dealing with 6 different types of traffic.

In [14]:
#CODE CHUNK 14

index_pred = index_pred%6
index_pred

array([2, 1, 5, ..., 1, 1, 2], dtype=int64)

In Code Chunk 15, we are similarly extracting the indices of the actual test data set values. 

In [15]:
#CODE CHUNK 15

index =  np.where(np.in1d(y_test, [1]))[0]

In Code Chunk 16, we are again taking the mod wrt 6, to get values between 0 and 5, for the actual test data.

In [16]:
#CODE CHUNK 16

index = index%6
index

array([2, 1, 4, ..., 1, 1, 2], dtype=int64)

In Code Chunk 17, we are generating the confusion matrix of the actual and predicted labels of the test data set.

In [17]:
#CODE CHUNK 17

matrix = confusion_matrix(index,index_pred)
matrix

array([[72582,     0,     0,     3,     0,     7],
       [   18, 57401,    24,     1,     0,     0],
       [   13,    27, 28710,     1,     0,     0],
       [    7,     0,     0, 27309,     0,     0],
       [   27,     0,     0,     1,    38, 70059],
       [    9,     0,     0,     1,     7, 79244]], dtype=int64)

In Code Chunk 18, we are generating a heatmap of the confusion matrix. We have analysed the heatmap in our report.  

In [18]:
#CODE CHUNK 18

import matplotlib.pyplot as plt
import seaborn as sn

plt.figure(figsize = (10,7))
ax = sn.heatmap(matrix, annot=True,fmt="d")



In Code Chunk 19, we calculate the sensitivity of each class of traffic in the network. 

In [19]:
#CODE CHUNK 19

def sensitivity(confusion_matrix,i):
    true_positives = confusion_matrix[i][i]
    false_negatives = sum(confusion_matrix[i]) - true_positives
    return true_positives/(true_positives+false_negatives)

print("The sensitivity is ")


for i in range(6):
    a = sensitivity(matrix,i)
    print(a)   

The sensitivity is 
0.9998622437734186
0.9992514448854537
0.9985739626447776
0.9997437399326402
0.0005418894830659536
0.9997855187292616


In Code Chunk 20, we similarly calculate the specificities of each class. 

In [20]:
#CODE CHUNK 20

#for i in range(6):
def specificity(confusion_matrix,i):
    a=np.array(confusion_matrix)
    cols = (np.sum(a, axis=0))
    rows = (np.sum(a, axis=1))
    true_positives = confusion_matrix[i][i]
    true_negatives = sum(sum(confusion_matrix)) - rows[i] - cols[i] + confusion_matrix[i][i]
    false_positives = cols[i] - true_positives
    return true_negatives/(true_negatives+false_positives)

print("The specificity is ")
    
for i in range(6):
    print(specificity(matrix,i))

The specificity is 
0.9997185209416616
0.9999028934165333
0.9999217573303602
0.9999772854857499
0.9999736211392654
0.7265482304822267


For Code Chunks 21 to 28. In the previous part, we notice that TCP and UDP are getting misclassified to a great extent. So, as a check, we are carrying out binary classification between them to see if they can be distinguished in this scenario. 

In [21]:
#CODE CHUNK 21

tcp_udp = df[df['Type'].str.contains("udp|tcp")]

In [22]:
#CODE CHUNK 22

tcp_udp['Type'] = tcp_udp['Type'].map({'tcp':0, 'udp':1})
tcp_udp_dataset = tcp_udp.values

C:\Users\seeml\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [23]:
#CODE CHUNK 23

pd.crosstab(tcp_udp.Type,columns='type')

col_0    type
Type         
0      279743
1      316447

In [24]:
#CODE CHUNK 24

scaler = preprocessing.StandardScaler()
X_tcpudp = scaler.fit_transform(tcp_udp.iloc[:,0:115])

In [25]:
#CODE CHUNK 25

Y_tcpudp = tcp_udp_dataset[:,115]

Xtcpudp_train, Xtcpudp_test, ytcpudp_train, ytcpudp_test =train_test_split(X_tcpudp,Y_tcpudp, test_size = 0.25)

In [26]:
#CODE CHUNK 26


model = Sequential()
model.add(Dense(200, input_dim=115, activation='softmax'))
model.add(Dense(250, activation='relu'))
model.add(Dense(1, activation='softmax'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(Xtcpudp_train, ytcpudp_train, epochs=5, batch_size=1500)

Epoch 1/5
447142/447142 [==============================] - 5s 10us/step - loss: 7.4778 - acc: 0.5309
Epoch 2/5
447142/447142 [==============================] - 4s 9us/step - loss: 7.4778 - acc: 0.5309
Epoch 3/5
447142/447142 [==============================] - 4s 9us/step - loss: 7.4778 - acc: 0.5309
Epoch 4/5
447142/447142 [==============================] - 4s 9us/step - loss: 7.4778 - acc: 0.5309
Epoch 5/5
447142/447142 [==============================] - 5s 11us/step - loss: 7.4778 - acc: 0.5309


In [27]:
#CODE CHUNK 27

predictions = model.predict(Xtcpudp_test)
rounded = [round(x[0]) for x in predictions]
pd.crosstab(rounded-ytcpudp_test,columns="Residual")

col_0  Residual
row_0          
0.0       79037
1.0       70011

In [28]:
#CODE CHUNK 28

pd.crosstab(ytcpudp_test,columns="Type")

col_0   Type
row_0       
0      70011
1      79037

In Code Chunks 29 to 31, we extract the data corresponding to TCP and UDP, and perform the Kruskal-Wallis Test on them to test the hypothesis that they are generated from the same distribution. We use a small subset of the data here, to obtain the results within a reasonable computation time.  

In [29]:
#CODE CHUNK 29

df_udp = df[df['Type'].str.contains("udp")]
df_tcp = df[df['Type'].str.contains("tcp")]

scaler = preprocessing.StandardScaler()
dataset_tcp = scaler.fit_transform(df_tcp.iloc[:,0:115])
dataset_udp = scaler.fit_transform(df_udp.iloc[:,0:115])

In [30]:
#CODE CHUNK 30

X1_tcp, X11_tcp =train_test_split(dataset_tcp, test_size = 0.001)
X1_udp, X11_udp =train_test_split(dataset_udp, test_size = 0.001)

In [31]:
#CODE CHUNK 31

pvalue = []

for i in range(len(X11_tcp)):
    for j in range(len(X11_udp)):
        a = (stats.kruskal(dataset_tcp[i], dataset_udp[j]))
        pvalue.append(a.pvalue)


In Code Chunk 32, we carry out Bonferroni correction on the list of p values obtained from the Kruskal-Wallis Test. 

In [32]:
#CODE CHUNK 32

q = 0
alpha = 0.05
n = len(X11_tcp) * len(X11_udp)

for i in range(len(pvalue)):
    if pvalue[i] < (alpha/n):
        q = q + 1
#print percentage of pvalue that being rejected(not the same distribution)         
print(q/len(pvalue))

0.02924740874267688


From the result of the hypothesis test, we decide to combine udp and tcp together.

In Code Chunks 33 to 46, we combine the TCP and UDP data into a common class, and carry out the same analysis as before. 

Note : In Code Chunk 41, we obtain the accuracy values after every 5 epochs. This is done to get an idea of how the precision of the model increases with increasing number of epochs. 

In [33]:
#CODE CHUNK 33

df1 = df
df1['Type'] = df.Type.replace(["tcp","udp"],"tcp&udp")

In [34]:
#CODE CHUNK 34

dataset1 = df1.values

In [35]:
#CODE CHUNK 35

scaler = preprocessing.StandardScaler()
X_scaled_1 = scaler.fit_transform(df1.iloc[:,0:115])
Y_1 = dataset1[:,115]
Z_1 = dataset1[:,116]

In [36]:
#CODE CHUNK 36

pd.crosstab(df1.Type,columns='type')

col_0      type
Type           
benign   290051
combo    229551
junk     116034
scan     110129
tcp&udp  596190

In [37]:
#CODE CHUNK 37

encoder = LabelEncoder()
encoder.fit(Y_1)
encoded_Y = encoder.transform(Y_1)
dummy_y1 = np_utils.to_categorical(encoded_Y)

In [38]:
#CODE CHUNK 38

X1_train, X1_test, y1_train, y1_test,z1_train,z1_test =train_test_split(X_scaled_1,dummy_y1, Z_1, test_size = 0.25)

In [39]:
#CODE CHUNK 39


model2 = Sequential()
model2.add(Dense(250, input_dim=115, activation='relu'))
model2.add(Dense(250, activation='relu'))
model2.add(Dense(25, activation='sigmoid'))
model2.add(Dense(5, activation='softmax'))

In [40]:
#CODE CHUNK 40

model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [41]:
#CODE CHUNK 41

epochs=list()
trainacc=list()
testacc=list()
deltaepochs=5
eon=0
for i in range(0,10) :
        print("epoch : " + str(eon))
        model2.fit(X1_train, y1_train, epochs=deltaepochs, batch_size=1500)
        scores = model2.evaluate(X1_train, y1_train)
        testscores = model2.evaluate(X1_test, y1_test)
        eon+=deltaepochs
        epochs.append(eon)
        trainacc.append(scores[1])
        testacc.append(testscores[1])
results=[epochs,
        trainacc,
        testacc]
print(results)

epoch : 0
Epoch 1/5
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.0630 - acc: 0.9735
Epoch 2/5
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.0112 - acc: 0.9972
Epoch 3/5
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.0060 - acc: 0.9981
Epoch 4/5
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.0048 - acc: 0.9983
Epoch 5/5
335489/335489 [==============================] - 9s 26us/step
epoch : 5
Epoch 1/5
1006466/1006466 [==============================] - 11s 11us/step - loss: 0.0028 - acc: 0.9991
Epoch 2/5
1006466/1006466 [==============================] - 11s 11us/step - loss: 0.0030 - acc: 0.9991
Epoch 3/5
1006466/1006466 [==============================] - 11s 11us/step - loss: 0.0022 - acc: 0.9993
Epoch 4/5
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.0026 - acc: 0.9992
Epoch 5/5
335489/335489 [==============================] - 9s 25us/step
epoc

In [42]:
#CODE CHUNK 42

predictions = model2.predict(X1_test)
predictions

array([[6.8660966e-09, 3.6776058e-08, 1.2188056e-07, 9.9999893e-01,
        9.1701094e-07],
       [1.5989679e-05, 2.9152309e-07, 6.1226025e-08, 2.5130524e-07,
        9.9998343e-01],
       [1.5989679e-05, 2.9152309e-07, 6.1226025e-08, 2.5130524e-07,
        9.9998343e-01],
       ...,
       [1.5989679e-05, 2.9152309e-07, 6.1226025e-08, 2.5130524e-07,
        9.9998343e-01],
       [1.3943638e-07, 2.5928302e-05, 9.9997091e-01, 1.3064137e-06,
        1.6678731e-06],
       [1.0818582e-08, 1.3886477e-04, 9.9986112e-01, 3.8549857e-08,
        6.3070780e-09]], dtype=float32)

In [43]:
#CODE CHUNK 43

prediction = predictions
for i in range(len(prediction)):
    a = 0
    indexpred = 0
    for j in range(5):
        if prediction[i][j] > a:
            a = prediction[i][j]
            indexpred = j
            
    for k in range(5):
        if k==indexpred:
            prediction[i][k] = 1
        else:
            prediction[i][k] = 0
print(prediction)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [44]:
#CODE CHUNK 44

index_pred = np.where(np.in1d(prediction, [1]))[0]
index_pred = index_pred%5
index =  np.where(np.in1d(y1_test, [1]))[0]
index = index%5

In [45]:
#CODE CHUNK 45

matrix = confusion_matrix(index,index_pred)
matrix

array([[ 72577,     13,      0,      0,     18],
       [     2,  57535,     39,      8,      0],
       [     1,     35,  28975,      1,      0],
       [     3,      8,      0,  27322,      1],
       [    17,      6,      0,      0, 148928]], dtype=int64)

In [46]:
#CODE CHUNK 46

for i in range(5):
    print(specificity(matrix,i))
    
for i in range(5):
    print(sensitivity(matrix,i))

0.9999125079408554
0.9997769021788021
0.9998727473839799
0.9999707939186449
0.9998981440778822
0.9995730498016747
0.999149069185885
0.9987246656555908
0.9995609863174069
0.9998455868037139


 From the confusion matrix and the values for sensitivity and specificity, we observe that the model has done an extremely good job of predicting the types of traffic in the network. <br/>
 

In Code Chunks 47 to 57, we are performing the same analysis as before, but on a slightly different training data set. This time, we have removed the observations corresponding to the 'Scan' attack from the training data. However, the test data set remains the same as before. Thus, we hope to get an idea about our model's predictive power, when it hasn't encountered a particular form of traffic beforehand.

Note : In cell 53, we have used a particular technique of identifying the unknown class in our test data. Briefly, it involves comparing the prediction values (which are basically the probability of that observation belonging to that particular class) to a threshold set by the user (0.5, for us). If all the predictions lie below 0.5, we claim that the prediction is an outlier, and thus corresponds to the unknown class we are trying to identify. <br/>
This technique has been explained in more detail (and referenced) in the main report.

In [47]:
#CODE CHUNK 47

scan_index = np.where(y1_train[:,3] == 1)

In [48]:
#CODE CHUNK 48

X2_train = np.delete(X1_train,scan_index,axis=0)
y2_train = np.delete(np.delete(y1_train,scan_index,axis=0),np.s_[3],1)
X2_test = X1_test
y2_test = y1_test


In [49]:
#CODE CHUNK 49

model3 = Sequential()
model3.add(Dense(250, input_dim=115, activation='relu'))
model3.add(Dense(250, activation='relu'))
model3.add(Dense(25, activation='sigmoid'))
model3.add(Dense(4, activation='softmax'))

In [50]:
#CODE CHUNK 50

model3.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [51]:
#CODE CHUNK 51

model3.fit(X2_train, y2_train, epochs=50, batch_size=1500)

Epoch 1/50
923671/923671 [==============================] - 11s 12us/step - loss: 0.0775 - acc: 0.9632
Epoch 2/50
923671/923671 [==============================] - 11s 12us/step - loss: 0.0186 - acc: 0.9954
Epoch 3/50
923671/923671 [==============================] - 12s 12us/step - loss: 0.0072 - acc: 0.9978
Epoch 4/50
923671/923671 [==============================] - 11s 12us/step - loss: 0.0056 - acc: 0.9980
Epoch 5/50
923671/923671 [==============================] - 12s 13us/step - loss: 0.0041 - acc: 0.9987
Epoch 6/50
923671/923671 [==============================] - 12s 13us/step - loss: 0.0035 - acc: 0.9988
Epoch 7/50
923671/923671 [==============================] - 12s 13us/step - loss: 0.0027 - acc: 0.9991
Epoch 8/50
923671/923671 [==============================] - 12s 13us/step - loss: 0.0025 - acc: 0.9991
Epoch 9/50
923671/923671 [==============================] - 12s 13us/step - loss: 0.0019 - acc: 0.9994
Epoch 10/50
923671/923671 [==============================] - 12s 13us/ste

In [52]:
#CODE CHUNK 52

predictions = model3.predict(X2_test)

In [53]:
#CODE CHUNK 53

prediction1 = predictions
threshold = 0.5

for i in range(len(prediction1)):
    for j in range(4):
        if prediction1[i][j] >= threshold:
            prediction1[i][j] = 1
        else:
            prediction1[i][j] = 0


In [54]:
#CODE CHUNK 54

prediction2 = np.insert(prediction1,3,0,axis=1)
for i in range(len(prediction2)):
    if sum(prediction2[i]) == 0:
        prediction2[i][3] = 1
prediction2

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)

In [55]:
#CODE CHUNK 55

index_pred = np.where(np.in1d(prediction2, [1]))[0]
index_pred = index_pred%5
index= np.where(np.in1d(y2_test, [1]))[0]
index = index%5

In [56]:
#CODE CHUNK 56

from sklearn.metrics import confusion_matrix
matrix3 = confusion_matrix(index,index_pred)
matrix3

array([[ 72595,      0,      0,      1,     12],
       [    10,  57523,     50,      1,      0],
       [    13,    433,  28564,      2,      0],
       [  6399,   1682,      0,    944,  18309],
       [    17,      2,      0,      1, 148931]], dtype=int64)

In [57]:
#CODE CHUNK 57

print("The sensitivity is ")   
for i in range(5):
    print(sensitivity(matrix3,i))
print("The specificity is ") 
for i in range(5):
    print(specificity(matrix3,i))

The sensitivity is 
0.9998209563684443
0.9989406779661016
0.9845581138839101
0.03453574303065779
0.9998657276554035
The specificity is 
0.9755060274420746
0.9923822889116785
0.999836855620487
0.9999837743992471
0.9017840868884625


We observe that the model **does not** do a very good job in classifying 'Scan' if it hasn't seen it before. However, we note that majority of the observations corresponding to 'Scan' (around 76%) are being misclassified as 'TCP UDP', with the next highest proportion going to benign, and some to Junk and Combo respectively. <br/>
We have discussed the implications of this in more detail in the report. 

As seen in the previous section, the prediction of 'Scan' wasn't very successful. In order to check if this was a one-off for the model, or if it misclassified every unseen attack, we decided to carry out the same analysis, but with the 'Combo' attack hidden from the training data set. As before, the test data set remains the same. <br/>
This analysis is provided in Code Chunks 58 to 66.

In [58]:
#CODE CHUNK 58

combo_index = np.where(y1_train[:,1] == 1)
X2_train = np.delete(X1_train,combo_index,axis=0)
y2_train = np.delete(np.delete(y1_train,combo_index,axis=0),np.s_[1],1)
X2_test = X1_test
y2_test = y1_test


In [59]:
#CODE CHUNK 59

model3 = Sequential()
model3.add(Dense(250, input_dim=115, activation='relu'))
model3.add(Dense(250, activation='relu'))
model3.add(Dense(25, activation='sigmoid'))
model3.add(Dense(4, activation='softmax'))

In [60]:
#CODE CHUNK 60

model3.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [61]:
#CODE CHUNK 61

model3.fit(X2_train, y2_train, epochs=50, batch_size=1500)

Epoch 1/50
834499/834499 [==============================] - 10s 12us/step - loss: 0.0276 - acc: 0.9945
Epoch 2/50
834499/834499 [==============================] - 9s 11us/step - loss: 0.0034 - acc: 0.9996
Epoch 3/50
834499/834499 [==============================] - 9s 11us/step - loss: 0.0018 - acc: 0.9997
Epoch 4/50
834499/834499 [==============================] - 10s 12us/step - loss: 0.0012 - acc: 0.9998
Epoch 5/50
834499/834499 [==============================] - 11s 13us/step - loss: 8.9014e-04 - acc: 0.9998
Epoch 6/50
834499/834499 [==============================] - 10s 12us/step - loss: 6.9997e-04 - acc: 0.9999
Epoch 7/50
834499/834499 [==============================] - 10s 12us/step - loss: 5.3657e-04 - acc: 0.9999 1s - loss:
Epoch 8/50
834499/834499 [==============================] - 11s 13us/step - loss: 4.5387e-04 - acc: 0.9999
Epoch 9/50
834499/834499 [==============================] - 11s 13us/step - loss: 4.7600e-04 - acc: 0.9999
Epoch 10/50
834499/834499 [=================

In [62]:
#CODE CHUNK 62

predictions = model3.predict(X2_test)
predictions

array([[1.5003640e-06, 8.0471573e-06, 9.9998808e-01, 2.3266318e-06],
       [1.2395269e-05, 1.6900100e-06, 7.8988108e-08, 9.9998581e-01],
       [1.2395269e-05, 1.6900100e-06, 7.8988108e-08, 9.9998581e-01],
       ...,
       [1.2395269e-05, 1.6900100e-06, 7.8988108e-08, 9.9998581e-01],
       [5.2193059e-07, 9.9999559e-01, 3.1246148e-06, 8.7264328e-07],
       [2.7143778e-07, 9.9999595e-01, 1.6527050e-06, 2.1866613e-06]],
      dtype=float32)

In [63]:
#CODE CHUNK 63

prediction1 = predictions
threshold = 0.5

for i in range(len(prediction1)):
    for j in range(4):
        if prediction1[i][j] >= threshold:
            prediction1[i][j] = 1
        else:
            prediction1[i][j] = 0


In [64]:
#CODE CHUNK 64

prediction2 = np.insert(prediction1,1,0,axis=1)
for i in range(len(prediction2)):
    if sum(prediction2[i]) == 0:
        prediction2[i][1] = 1
prediction2

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)

In [65]:
#CODE cHUNK 65

index_pred = np.where(np.in1d(prediction2, [1]))[0]
index_pred = index_pred%5
index= np.where(np.in1d(y2_test, [1]))[0]
index = index%5

In [66]:
#CODE CHUNK 66

matrix = confusion_matrix(index,index_pred)
print(matrix)

for i in range(5):
    print(sensitivity(matrix,i))
    
for i in range(5):
    print(specificity(matrix,i))

[[ 72595      0      0      1     12]
 [     5      0  57577      1      1]
 [     6      0  29006      0      0]
 [     5      3      0  27326      0]
 [     7      2      0      0 148942]]
0.9998209563684443
0.0
0.999793189025231
0.9997073242116046
0.9999395774449316
0.9999125079408554
0.999982008240226
0.8121327212156214
0.9999935097596988
0.9999303091059194


We observe that the classification in this case is worse than 'Scan'. More than 99% of the 'Combo' observations are being misclassified as 'Junk' traffic. An extremely low proportion is classified as 'benign' (less than 0.01%). <br/>

In the third variant of our model, we are considering the same training and test data as before. Here, we will be removing all the observations corresponding to a particular device. Then we will be attempting to classify the test data on the basis of the device labels, and check the performance of our model. <br/>
In the beginning however, we are running a normal neural network model (similar to our first model) to try and predict the device labels, after learning on the **entire** training data. <br/>
This analysis is provided in Code Chunks 67 to 76. 

In [67]:
#CODE CHUNK 67

encoder = LabelEncoder()
encoder.fit(Z_1)
encoded_Z = encoder.transform(Z_1)
dummy_z1 = np_utils.to_categorical(encoded_Z)

In [68]:
#CODE CHUNK 68

X3_train, X3_test,z3_train,z3_test =train_test_split(X_scaled_1,dummy_z1, test_size = 0.25)

In [69]:
#CODE CHUNK 69

model4 = Sequential()
model4.add(Dense(250, input_dim=115, activation='relu'))
model4.add(Dense(250, activation='relu'))
model4.add(Dense(25, activation='sigmoid'))
model4.add(Dense(4, activation='softmax'))

In [70]:
#CODE CHUNK 70

model4.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [71]:
#CODE CHUNK 71

model4.fit(X3_train, z3_train, epochs=50, batch_size=1500)

Epoch 1/50
1006466/1006466 [==============================] - 12s 11us/step - loss: 0.4176 - acc: 0.8010
Epoch 2/50
1006466/1006466 [==============================] - 11s 11us/step - loss: 0.4050 - acc: 0.8037
Epoch 3/50
1006466/1006466 [==============================] - 11s 11us/step - loss: 0.4039 - acc: 0.8038
Epoch 4/50
1006466/1006466 [==============================] - 11s 11us/step - loss: 0.4032 - acc: 0.8038
Epoch 5/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.4028 - acc: 0.8039
Epoch 6/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.4025 - acc: 0.8039
Epoch 7/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.4022 - acc: 0.8039
Epoch 8/50
1006466/1006466 [==============================] - 12s 12us/step - loss: 0.4019 - acc: 0.8040
Epoch 9/50
1006466/1006466 [==============================] - 13s 13us/step - loss: 0.4016 - acc: 0.8040
Epoch 10/50
1006466/1006466 [==========================

In [72]:
#CODE CHUNK 72

predictions = model4.predict(X3_test)
predictions

array([[3.2808965e-01, 3.3462146e-01, 3.3728662e-01, 2.2440001e-06],
       [3.2808965e-01, 3.3462146e-01, 3.3728662e-01, 2.2440001e-06],
       [1.2789493e-04, 4.5839854e-04, 9.9834740e-01, 1.0664049e-03],
       ...,
       [2.4626538e-01, 2.5308105e-01, 2.4878961e-01, 2.5186402e-01],
       [3.2808965e-01, 3.3462146e-01, 3.3728662e-01, 2.2440001e-06],
       [2.8175911e-01, 2.5617385e-01, 2.6322564e-01, 1.9884133e-01]],
      dtype=float32)

In [73]:
#CODE CHUNK 73

prediction = predictions
for i in range(len(prediction)):
    a = 0
    indexpred = 0
    for j in range(4):
        if prediction[i][j] > a:
            a = prediction[i][j]
            indexpred = j
            
    for k in range(4):
        if k==indexpred:
            prediction[i][k] = 1
        else:
            prediction[i][k] = 0
print(prediction)

[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [74]:
#CODE CHUNK 74

index_pred = np.where(np.in1d(prediction, [1]))[0]
index_pred = index_pred%4
index =  np.where(np.in1d(z3_test, [1]))[0]
index = index%4

In [75]:
#CODE CHUNK 75

matrix4 = confusion_matrix(index,index_pred)
matrix4

array([[18021,  5801, 62847,  4603],
       [ 4577, 49861, 63408,  4238],
       [ 4831,  4947, 67117,  4433],
       [ 4014,  5621, 13851, 17319]], dtype=int64)

In [76]:
#CODE CHUNK 76

print("The sensitivity is ")   
for i in range(4):
    print(sensitivity(matrix4,i))
print("The specificity is ") 
for i in range(4):
    print(specificity(matrix4,i))

The sensitivity is 
0.19744280830922956
0.4084155171848891
0.8252631320086563
0.4244332802352653
The specificity is 
0.9450406810336709
0.9232960802230501
0.44875098854662987
0.9549551383855248


From the confusion matrixc, we observe that the model does not do a very good job of classifying the observations according to their device labels. <br/>
From the sensitivity values, we see that the highest value is 0.77 (corresponding to Baby Monitor). This means that for that device, only 77% of the observations were correctly classfied, and the model performed even more poorly for the other devices. 

In this section, we are removing all the observations corresponding to the 'doorbell' device from the training data set and attempting to predict device labels based on the same test data set. <br/>
This analysis is provided in Code Chunks 77 to 81.

In [77]:
#CODE CHUNK 77

doorbell_index = np.where(z3_train[:,0] == 1)
X4_train = np.delete(X3_train,doorbell_index,axis=0)
z4_train = np.delete(np.delete(z3_train,doorbell_index,axis=0),np.s_[0],1)
X4_test = X3_test
z4_test = z3_test

In [78]:
#CODE CHUNK 78

model5 = Sequential()
model5.add(Dense(250, input_dim=115, activation='relu'))
model5.add(Dense(250, activation='relu'))
model5.add(Dense(25, activation='sigmoid'))
model5.add(Dense(3, activation='softmax'))
model5.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [79]:
#CODE CHUNK 79

model5.fit(X4_train, z4_train, epochs=50, batch_size=1500)

Epoch 1/50
731540/731540 [==============================] - 9s 12us/step - loss: 0.4324 - acc: 0.7442
Epoch 2/50
731540/731540 [==============================] - 9s 13us/step - loss: 0.4124 - acc: 0.7482
Epoch 3/50
731540/731540 [==============================] - 9s 13us/step - loss: 0.4106 - acc: 0.7487
Epoch 4/50
731540/731540 [==============================] - 10s 13us/step - loss: 0.4098 - acc: 0.7493
Epoch 5/50
731540/731540 [==============================] - 10s 13us/step - loss: 0.4090 - acc: 0.7492
Epoch 6/50
731540/731540 [==============================] - 9s 13us/step - loss: 0.4084 - acc: 0.7492
Epoch 7/50
731540/731540 [==============================] - 10s 13us/step - loss: 0.4078 - acc: 0.7492
Epoch 8/50
731540/731540 [==============================] - 9s 13us/step - loss: 0.4070 - acc: 0.7499
Epoch 9/50
731540/731540 [==============================] - 9s 13us/step - loss: 0.4068 - acc: 0.7501
Epoch 10/50
731540/731540 [==============================] - 9s 12us/step - los

In [80]:
#CODE CHUNK 80

predictions = model5.predict(X4_test)
prediction1 = predictions
threshold = 0.5
for i in range(len(prediction1)):
    for j in range(3):
        if prediction1[i][j] >= threshold:
            prediction1[i][j] = 1
        else:
            prediction1[i][j] = 0
prediction2 = np.insert(prediction1,0,0,axis=1)
for i in range(len(prediction2)):
    if sum(prediction2[i]) == 0:
        prediction2[i][0] = 1
index_pred = np.where(np.in1d(prediction2, [1]))[0]
index_pred = index_pred%4
index= np.where(np.in1d(y1_test, [1]))[0]
index = index%4
#confusionmatrix
matrix5 = confusion_matrix(index,index_pred)
print(matrix5)

[[26654 12315 40485  4067]
 [27126 12293 40696  4141]
 [26999 12107 40653  4103]
 [26684 12514 40488  4164]]


In [81]:
#CODE CHUNK 81

print("The sensitivity is ")   
for i in range(4):
    print(sensitivity(matrix5,i))
print("The specificity is ") 
for i in range(4):
    print(specificity(matrix5,i))

The sensitivity is 
0.3191293207696268
0.14590058868211167
0.4847606782571367
0.04966010733452594
The specificity is 
0.6792886398272796
0.8529810972284692
0.5164708079816553
0.9510767408867465


Similar to the previous analysis, we see that the model does not do a very good job of predicting the unknown device from the test data set. The percentage of correctly classified observations for each class range from 29% to 65%, which is not very good for a system designed to detect malicious traffic. 

Note : A more detailed discussion of the results obtained from each of the models is provided in the main report. 